name = "SampleJuliaProj"
uuid = "1034c065-f61e-438e-9130-f1af12b3167e"
authors = ["Nivedita Rethnakar et al."]
version = "0.1.0"

[compat]
julia = "1.7.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
